// ARCHIVO GENERADO — NO EDITAR A MANO.
// Regenerar con:  npx tsx scripts/construir-catalogo-repositorio.ts
// Fuente: scripts/data/drive-catalogo.json (árbol de la carpeta de Drive del estudio).
//
// Índice temático liviano (100 materias). A diferencia de catalogo.ts NO es
// server-only: es chico y la UI lo puede importar para pintar el árbol de la
// biblioteca sin esperar a la API.

import type { Coleccion, Materia } from "./types";

export const MATERIAS: Materia[] = [
  { slug: "doc-aborto", label: "Aborto", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-abuso-sexual-y-violacion", label: "Abuso sexual y violación", coleccion: "doctrina", cantidad: 3 },
  { slug: "doc-administracion-publica", label: "Administración pública", coleccion: "doctrina", cantidad: 9 },
  { slug: "doc-analisis-economico-del-derecho-penal-aedp", label: "Análisis económico del derecho penal (AEDP)", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-armas", label: "Armas", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-autoria-y-participacion", label: "Autoría y participación", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-bien-juridico", label: "Bien jurídico", coleccion: "doctrina", cantidad: 3 },
  { slug: "doc-criminologia", label: "Criminología", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-delitos-contra-el-estado-civil", label: "Delitos contra el estado civil", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-delitos-contra-el-honor", label: "Delitos contra el honor", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-delitos-contra-el-orden-publico", label: "Delitos contra el orden público", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-delitos-contra-la-fe-publica", label: "Delitos contra la fe pública", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-delitos-contra-la-libertad", label: "Delitos contra la libertad", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-delitos-contra-la-propiedad", label: "Delitos contra la propiedad", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-delitos-contra-la-salud-publica", label: "Delitos contra la salud pública", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-delitos-contra-la-seguridad-nacional", label: "Delitos contra la seguridad nacional", coleccion: "doctrina", cantidad: 3 },
  { slug: "doc-derecho-penal-internacional", label: "Derecho penal internacional", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-derecho-procesal-penal-procedimiento-bonaerense-ley-11-922", label: "Derecho Procesal Penal — Procedimiento Bonaerense (Ley 11.922)", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-derechos-humanos", label: "Derechos humanos", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-determinacion-de-la-pena", label: "Determinación de la pena", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-dolo-culpa-imprudencia", label: "Dolo, culpa, imprudencia", coleccion: "doctrina", cantidad: 4 },
  { slug: "doc-ejecucion-de-la-pena", label: "Ejecución de la pena", coleccion: "doctrina", cantidad: 3 },
  { slug: "doc-estado-de-necesidad", label: "Estado de necesidad", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-estupefacientes", label: "Estupefacientes", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-etapa-intermedia-control-de-la-acusacion-y-elevacion-a-juici", label: "Etapa intermedia – Control de la acusación y elevación a juicio", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-flagrancia", label: "Flagrancia", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-homicidio-simple-y-agravado", label: "Homicidio simple y agravado", coleccion: "doctrina", cantidad: 4 },
  { slug: "doc-hurto", label: "Hurto", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-imputacion-objetiva", label: "Imputación objetiva", coleccion: "doctrina", cantidad: 8 },
  { slug: "doc-investigacion-penal-preparatoria-ipp-y-juicio-oral", label: "Investigación Penal Preparatoria (IPP) y juicio oral", coleccion: "doctrina", cantidad: 3 },
  { slug: "doc-juicio-abreviado", label: "Juicio abreviado", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-juicio-por-jurados", label: "Juicio por jurados", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-jurisdiccion", label: "Jurisdicción", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-legitima-defensa", label: "Legítima defensa", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-lesiones", label: "Lesiones", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-materia-recursiva", label: "Materia recursiva", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-medidas-de-coercion", label: "Medidas de coerción", coleccion: "doctrina", cantidad: 4 },
  { slug: "doc-medidas-no-privativas-de-libertad", label: "Medidas no privativas de libertad", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-minoridad", label: "Minoridad", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-nulidades", label: "Nulidades", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-omision-y-accion", label: "Omisión y acción", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-orden-publico", label: "Orden público", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-penal-de-la-empresa", label: "Penal de la empresa", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-penal-economico", label: "Penal económico", coleccion: "doctrina", cantidad: 8 },
  { slug: "doc-simulacion-con-ia-y-argumentacion-juridica", label: "Simulación con IA y argumentación jurídica", coleccion: "doctrina", cantidad: 1 },
  { slug: "doc-teoria-del-delito", label: "Teoría del delito", coleccion: "doctrina", cantidad: 2 },
  { slug: "doc-teorias-de-la-pena", label: "Teorías de la pena", coleccion: "doctrina", cantidad: 6 },
  { slug: "jur-aborto", label: "Aborto", coleccion: "jurisprudencia", cantidad: 4 },
  { slug: "jur-accion-penal-fiscalia", label: "Acción penal — Fiscalía", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-accion-penal-querella", label: "Acción penal — Querella", coleccion: "jurisprudencia", cantidad: 3 },
  { slug: "jur-actio-libera-in-causa", label: "Actio libera in causa", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-ambito-espacial-de-la-ley-penal", label: "Ámbito espacial de la ley penal", coleccion: "jurisprudencia", cantidad: 5 },
  { slug: "jur-amenaza-coaccion-e-intimidacion", label: "Amenaza, coacción e intimidación", coleccion: "jurisprudencia", cantidad: 11 },
  { slug: "jur-armas-tenencia-y-portacion", label: "Armas (tenencia y portación)", coleccion: "jurisprudencia", cantidad: 6 },
  { slug: "jur-autoria-y-participacion", label: "Autoría y participación", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-bagatela-principio-de-insignificancia", label: "Bagatela (principio de insignificancia)", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-carceles", label: "Cárceles", coleccion: "jurisprudencia", cantidad: 3 },
  { slug: "jur-casacion", label: "Casación", coleccion: "jurisprudencia", cantidad: 3 },
  { slug: "jur-competencia-penal-federal", label: "Competencia penal federal", coleccion: "jurisprudencia", cantidad: 4 },
  { slug: "jur-crimen-organizado", label: "Crimen organizado", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-culpabilidad", label: "Culpabilidad", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-deber-de-fundamentacion", label: "Deber de fundamentación", coleccion: "jurisprudencia", cantidad: 4 },
  { slug: "jur-debido-proceso", label: "Debido proceso", coleccion: "jurisprudencia", cantidad: 11 },
  { slug: "jur-defraudacion", label: "Defraudación", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-delitos-sexuales", label: "Delitos sexuales", coleccion: "jurisprudencia", cantidad: 4 },
  { slug: "jur-derecho-de-defensa", label: "Derecho de defensa", coleccion: "jurisprudencia", cantidad: 2 },
  { slug: "jur-determinacion-de-la-pena", label: "Determinación de la pena", coleccion: "jurisprudencia", cantidad: 9 },
  { slug: "jur-doble-conforme", label: "Doble conforme", coleccion: "jurisprudencia", cantidad: 2 },
  { slug: "jur-ejecucion-de-la-pena", label: "Ejecución de la pena", coleccion: "jurisprudencia", cantidad: 2 },
  { slug: "jur-estupefacientes", label: "Estupefacientes", coleccion: "jurisprudencia", cantidad: 4 },
  { slug: "jur-extradicion", label: "Extradición", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-garantias-constitucionales", label: "Garantías constitucionales", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-genero", label: "Género", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-homicidio", label: "Homicidio", coleccion: "jurisprudencia", cantidad: 11 },
  { slug: "jur-homicidio-preterintencional", label: "Homicidio preterintencional", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-in-dubio-pro-reo", label: "In dubio pro reo", coleccion: "jurisprudencia", cantidad: 3 },
  { slug: "jur-inimputabilidad", label: "Inimputabilidad", coleccion: "jurisprudencia", cantidad: 2 },
  { slug: "jur-iter-criminis", label: "Iter criminis", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-legitima-defensa", label: "Legítima defensa", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-lesa-humanidad", label: "Lesa humanidad", coleccion: "jurisprudencia", cantidad: 2 },
  { slug: "jur-lesiones", label: "Lesiones", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-ley-penal-mas-benigna", label: "Ley penal más benigna", coleccion: "jurisprudencia", cantidad: 5 },
  { slug: "jur-minoridad", label: "Minoridad", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-non-bis-in-idem", label: "Non bis in idem", coleccion: "jurisprudencia", cantidad: 2 },
  { slug: "jur-omision", label: "Omisión", coleccion: "jurisprudencia", cantidad: 5 },
  { slug: "jur-peculado", label: "Peculado", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-pena-de-muerte-estandares-internacionales", label: "Pena de muerte (estándares internacionales)", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-penal-ambiental", label: "Penal ambiental", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-penal-economico", label: "Penal económico", coleccion: "jurisprudencia", cantidad: 58 },
  { slug: "jur-principio-acusatorio", label: "Principio acusatorio", coleccion: "jurisprudencia", cantidad: 9 },
  { slug: "jur-principio-de-inocencia", label: "Principio de inocencia", coleccion: "jurisprudencia", cantidad: 4 },
  { slug: "jur-prision-domiciliaria", label: "Prisión domiciliaria", coleccion: "jurisprudencia", cantidad: 6 },
  { slug: "jur-prision-perpetua", label: "Prisión perpetua", coleccion: "jurisprudencia", cantidad: 6 },
  { slug: "jur-prision-preventiva", label: "Prisión preventiva", coleccion: "jurisprudencia", cantidad: 14 },
  { slug: "jur-prueba", label: "Prueba", coleccion: "jurisprudencia", cantidad: 9 },
  { slug: "jur-regimen-penal-juvenil", label: "Régimen penal juvenil", coleccion: "jurisprudencia", cantidad: 3 },
  { slug: "jur-reincidencia", label: "Reincidencia", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-robo", label: "Robo", coleccion: "jurisprudencia", cantidad: 1 },
  { slug: "jur-suspension-del-juicio-a-prueba-probation", label: "Suspensión del juicio a prueba (probation)", coleccion: "jurisprudencia", cantidad: 7 },
  { slug: "jur-victima", label: "Víctima", coleccion: "jurisprudencia", cantidad: 2 },
];

// Documentos ÚNICOS por colección. NO se puede derivar sumando `cantidad` de
// MATERIAS: un documento que vive en varias carpetas de Drive cuenta una vez por
// materia, así que esa suma da de más y contradice el total del header.
export const DOCUMENTOS_POR_COLECCION: Record<Coleccion, number> = {
  jurisprudencia: 241,
  doctrina: 104,
};
